<?php

return [ 'titles' => [['value' => 'Mr', 'title' => 'MR.'],
    ['value' => 'Miss', 'title' => 'MISS.'],
    ['value' => 'Mrs', 'title' => 'MRS.'],
    ['value' => 'Mal', 'title' => 'MAL.'],
    ['value' => 'Dr', 'title' => 'DR.'],
    ['value' => 'Dr.(Mrs)', 'title' => 'DR.(MRS)'],
    ['value' => 'Prof', 'title' => 'PROF.'],
    ['value' => 'Engr', 'title' => 'ENGR.'],
    ['value' => 'Engr.Dr', 'title' => 'ENGR.DR.'],
    ['value' => 'Engr.Prof', 'title' => 'ENGR.PROF.']
],
    'genders' => [['value' => 1, 'title' => 'Male'],
        ['value' => 2, 'title' => 'Female'],
    ],
    'religion' => [['value' => 1, 'title' => 'Christianity'],
        ['value' => 2, 'title' => 'Islam'],
        ['value' => 3, 'title' => 'Others'],
    ],
    'marital' => [['value' => 1, 'title' => 'Single'],
        ['value' => 2, 'title' => 'Married'],
        ['value' => 3, 'title' => 'Divorced'],
        ['value' => 4, 'title' => 'Widowed'],
        ['value' => 5, 'title' => 'Separated'],
    ],
];